defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

agent:
  seed: 2
  lr: 0.001
  gamma: 0.99
  tau: 0.005
  fc1_dim: 400
  fc2_dim: 300
  buffer_size: 100000
  batch_size: 128
  on_policy: False
  replay_buffer: True
  target_networks: True
  noise:
    mu: 0.0
    theta: 0.15
    sigma: 0.2
episodes: 500
env: 'Pendulum-v1'
output_dir: output
name: "part4"
infer_steps: 200
fps: 30
