defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

agent:
  lr: 0.001
  gamma: 0.99
  tau: 0.005
  noise_scale: 0.1
  hidden_dim: 128
  buffer_size: 10000
  batch_size: 128
  on_policy: False
  replay_buffer: True
  target_networks: True
episodes: 1000
env: 'Pendulum-v1'
output_dir: output
name: "part4"
infer_steps: 200
fps: 30